export const PROVIDE_GRAPHQL_POLICY = Symbol('PROVIDE_GRAPHQL_POLICY')

export const PROVIDE_GRAPHQL_LINKS = Symbol('PROVIDE_GRAPHQL_LINKS')

export const PROVIDE_GRAPHQL_SCHEMAS = Symbol('PROVIDE_GRAPHQL_SCHEMAS')

export const PROVIDE_GRAPHQL_RESOLVERS = Symbol('PROVIDE_GRAPHQL_RESOLVERS')

export const PROVIDE_GRAPHQL_STORE_FRAGMENTS = Symbol('PROVIDE_GRAPHQL_STORE_FRAGMENTS')

export const PROVIDE_GRAPHQL_STORE_POSSIBLE_TYPES = Symbol('PROVIDE_GRAPHQL_STORE_POSSIBLE_TYPES')

export const PROVIDE_GRAPHQL_FRAGMENTS = Symbol('PROVIDE_GRAPHQL_FRAGMENTS')
