export const PROVIDE_GRAPHQL_POLICY = Symbol('PROVIDE_GRAPHQL_POLICY')

export const PROVIDE_GRAPHQL_LINKS = Symbol('PROVIDE_GRAPHQL_LINKS')

export const PROVIDE_GRAPHQL_SCHEMAS = Symbol('PROVIDE_GRAPHQL_SCHEMAS')

export const PROVIDE_GRAPHQL_RESOLVERS = Symbol('PROVIDE_GRAPHQL_RESOLVERS')
