#!/usr/bin/env node

const { spawnSync } = require('child_process')
const { join } = require('path')
const { existsSync } = require('fs');

if (existsSync(join(process.cwd(), '.gitmodules'))) {
    spawnSync(`git`, ['submodule', 'update', '--remote'], { stdio: 'inherit', cwd: process.cwd() })
}

spawnSync(`node`, [`${join(__dirname, 'install')}`], { stdio: 'inherit', cwd: __dirname })
spawnSync(`node`, [`${join(__dirname, 'build')}`], { stdio: 'inherit', cwd: __dirname })
spawnSync(`node`, [`${join(__dirname, 'upgrade')}`], { stdio: 'inherit' })
