#!/usr/bin/env node

const { spawnSync } = require('child_process')

console.log('Installing PWA...')
spawnSync(`yarn`, ['install'], { stdio: 'inherit', cwd: __dirname })
console.log('Installed PWA.')
