#!/usr/bin/env node

const { spawnSync } = require('child_process')
const { readdirSync } = require('fs')
const { join } = require('path')

console.log('Upgrading PWA...')
const packages = readdirSync(join(__dirname, 'packages')).reduce((result, name) => {

	const root = join(__dirname, 'packages', name)
	const config = require(join(root, 'package.json'))

	if (config && config.name) {
		if (__dirname.startsWith(process.cwd())) {
			result.push(`${config.name}@portal:${join('.', root.substring(process.cwd().length))}`)
		} else {
			result.push(`${config.name}@portal:${root}`)
		}
	}

	return result
}, [])

spawnSync(`yarn`, ['add', ...packages], { stdio: 'inherit', cwd: process.cwd() })
spawnSync(`yarn`, [], { stdio: 'inherit', cwd: process.cwd() })

console.log('Upgraded PWA. Be happy! <3')
