image: php:7.3.15
pipelines:
    custom:
        deploy_develop:
            - step:
                name: Deploy develop to M2 staging
                deployment: Staging
                script:
                  - apt-get update && apt-get install -y unzip openssh-client rsync git
                  - curl -LO https://deployer.org/deployer.phar
                  - mv deployer.phar /usr/local/bin/dep
                  - chmod +x /usr/local/bin/dep
                  - git clone $DEPLOYER_REPO deploy
                  - cd deploy/staging
                  - ./frontend.sh develop $DEPLOY_STORE
        deploy_custom_branch:
            - step:
                name: Deploy selected branch to staging
                deployment: Staging
                script:
                  - apt-get update && apt-get install -y unzip openssh-client rsync git
                  - export DP_BRANCH=$(git rev-parse --abbrev-ref HEAD)
                  - curl -LO https://deployer.org/deployer.phar
                  - mv deployer.phar /usr/local/bin/dep
                  - chmod +x /usr/local/bin/dep
                  - git clone $DEPLOYER_REPO deploy
                  - cd deploy/staging
                  - ./frontend.sh $DP_BRANCH $DEPLOY_STORE
